# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  containers-auth.yaml
#   timestamp: 2026-09-28T13:09:56+00:00

from __future__ import annotations

from base64 import b64encode
from typing import TYPE_CHECKING, Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel

if TYPE_CHECKING:
    from pathlib import Path


class Auth(BaseModel):
    """
    Inline entry corresponding to the Go Auth struct. An empty object is allowed, including as a credential-helper marker.
    """

    model_config = ConfigDict(extra="allow", populate_by_name=True)
    auth: Annotated[str | None, Field(json_schema_extra={"contentEncoding": "base64"})] = None
    """
    Standard base64 representation of username:password. Base64 is encoding, not encryption. The decoded value must be checked at runtime; the password may contain colons.
    """
    identitytoken: str | None = None
    """
    Identity token field present in the Go struct. Structural acceptance alone does not guarantee that an identitytoken-only entry is usable by the runtime credential decoder.
    """


class ContainersAuth(BaseModel):
    """
    Modern auth-file envelope corresponding to the Go ContainersAuth struct.
    """

    model_config = ConfigDict(extra="allow", populate_by_name=True)
    auths: dict[str, Auth] | None = None
    """
    Map from registry host[:port], namespace, or repository to an inline credential object. Repository matching is performed at runtime, most-specific first. Legacy URL-shaped keys may also be read by the implementation; no key regex is imposed here.
    """
    cred_helpers: Annotated[dict[str, str] | None, Field(alias="credHelpers")] = None
    """
    Map from registry host[:port] to the suffix of a -credential- executable. Helpers are looked up by registry, not repository namespace. Existence and execution are runtime concerns.
    """

    def add_auth(
        self,
        hostname: str,
        username: str,
        password: str,
    ) -> None:
        """Add or replace inline credentials in this configuration.

        Other auth entries and credential helpers are preserved. Call this
        before constructing the adapter, which snapshots the configuration.
        """
        credentials = b64encode(f"{username}:{password}".encode()).decode("ascii")
        if self.auths is None:
            self.auths = {}
        self.auths[hostname] = Auth(auth=credentials)

    @staticmethod
    def get_instance(authfile: Path) -> ContainersAuth:
        """Load and validate a registry authentication JSON file.

        Args:
            authfile: Path to the authentication file.

        Raises:
            OSError: If the file cannot be read.
            pydantic.ValidationError: If the JSON or configuration is invalid.
        """
        return ContainersAuth.model_validate_json(authfile.read_bytes())


class ContainersRegistryAuthenticationFile(RootModel[ContainersAuth]):
    root: Annotated[ContainersAuth, Field(title="Containers registry authentication file")]
    """
    Unofficial structural JSON Schema derived from dockerConfigFile and dockerAuthConfig in podman-container-tools/container-libs. Describes canonical auth.json objects, not every input accepted by Go"s encoding/json decoder.
    """
