# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  containers-auth.yaml
#   timestamp: 2026-09-28T13:09:56+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Auth(BaseModel):
    """
    Inline entry corresponding to the Go Auth struct. An empty object is allowed, including as a credential-helper marker.
    """

    model_config = ConfigDict(extra="allow", populate_by_name=True)
    auth: Annotated[str | None, Field(json_schema_extra={"contentEncoding": "base64"})] = None
    """
    Standard base64 representation of username:password. Base64 is encoding, not encryption. The decoded value must be checked at runtime; the password may contain colons.
    """
    identitytoken: str | None = None
    """
    Identity token field present in the Go struct. Structural acceptance alone does not guarantee that an identitytoken-only entry is usable by the runtime credential decoder.
    """


class ContainersAuth(BaseModel):
    """
    Modern auth-file envelope corresponding to the Go ContainersAuth struct.
    """

    model_config = ConfigDict(extra="allow", populate_by_name=True)
    auths: dict[str, Auth] | None = None
    """
    Map from registry host[:port], namespace, or repository to an inline credential object. Repository matching is performed at runtime, most-specific first. Legacy URL-shaped keys may also be read by the implementation; no key regex is imposed here.
    """
    cred_helpers: Annotated[dict[str, str] | None, Field(alias="credHelpers")] = None
    """
    Map from registry host[:port] to the suffix of a -credential- executable. Helpers are looked up by registry, not repository namespace. Existence and execution are runtime concerns.
    """


class ContainersRegistryAuthenticationFile(RootModel[ContainersAuth]):
    root: Annotated[ContainersAuth, Field(title="Containers registry authentication file")]
    """
    Unofficial structural JSON Schema derived from dockerConfigFile and dockerAuthConfig in podman-container-tools/container-libs. Describes canonical auth.json objects, not every input accepted by Go"s encoding/json decoder.
    """
